### ISSUE TITLE
it

### ISSUE THREAD

**Issue by Gnuxie** [Gnuxie/Draupnir#64]
isn

**Comment by Mikaela** [comment]
>!gh create it isn't obvious what the ignore reaction is supposed to do on abuse reports.
> 
> Context: https://matrix.to/#/!IaWNErZAgQUhGqJXjX%3Amatrix.org/%24jUv9VWgF0vtSOOG7L7SA-ZGOZY1KzTuk3DaMhARAuyY

- https://matrix.to/#/!IaWNErZAgQUhGqJXjX%3Amatrix.org/%242-PBpQpZ8bJkaYhJxERg8unExSBL9qytB7R2OX26mY0

**Comment by Mikaela** [comment]
over

**Comment by Gnuxie** [comment]
Fixed in #65

**Comment by Gnuxie** [comment]
is over now
